/**
 * @file src/theme/ThemeProvider.tsx
 * @description Custom ThemeProvider wrapper component that distributes design
 * tokens to all child components via React Context.
 *
 * Wraps MUI's ThemeProvider with CssBaseline injection for consistent baseline
 * styling. This is the single entry point consumers use to theme the entire
 * component library.
 *
 * Architecture placement: Theme Layer.
 * - Depends on: createCustomTheme (sibling), types (sibling), @mui/material, react
 * - Depended on by: barrel exports (src/theme/index.ts, src/index.ts)
 * - Never imports from: component layer, infrastructure layer, or barrel indexes
 *
 * Named exports only (no default exports) per library convention.
 *
 * @module theme/ThemeProvider
 */

import React from 'react';
import { ThemeProvider as MUIThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

import { createCustomTheme } from './createCustomTheme';
import type { ThemeProviderProps } from './types';

// ---------------------------------------------------------------------------
// Re-export ThemeProviderProps for barrel export chain
// ---------------------------------------------------------------------------

/**
 * Re-exported from `./types` so that consumers importing from this module
 * (or the barrel `src/theme/index.ts`) have access to the props interface
 * without needing a separate import path.
 */
export type { ThemeProviderProps };

// ---------------------------------------------------------------------------
// ThemeProvider Component
// ---------------------------------------------------------------------------

/**
 * ThemeProvider — top-level context provider that distributes the library's
 * design tokens to all child wrapper components.
 *
 * Wraps MUI's native ThemeProvider (aliased as MUIThemeProvider) with:
 * 1. Automatic default theme generation via `createCustomTheme()` when no
 *    `theme` prop is provided
 * 2. `CssBaseline` injection for consistent cross-browser baseline styling
 *    (CSS reset/normalization)
 *
 * The component follows the Single ThemeProvider entry point pattern — consumers
 * wrap their application root with this component once, and all descendant
 * wrapper components automatically receive the theme context via MUI's
 * `useTheme()` hook and `sx` prop system.
 *
 * @example Default theme (no props):
 * ```tsx
 * import { ThemeProvider, Button } from 'material-ui-component-lib-project-1';
 *
 * function App() {
 *   return (
 *     <ThemeProvider>
 *       <Button variant="contained">Hello</Button>
 *     </ThemeProvider>
 *   );
 * }
 * ```
 *
 * @example Custom theme:
 * ```tsx
 * import { ThemeProvider, createCustomTheme } from 'material-ui-component-lib-project-1';
 *
 * const myTheme = createCustomTheme({
 *   palette: { primary: { main: '#ff5722' } },
 * });
 *
 * function App() {
 *   return (
 *     <ThemeProvider theme={myTheme}>
 *       <Button variant="contained">Custom Theme</Button>
 *     </ThemeProvider>
 *   );
 * }
 * ```
 *
 * @param props - ThemeProviderProps containing optional theme and required children.
 * @param props.theme - Optional MUI Theme object created via `createCustomTheme()`.
 *   When omitted, the library's default theme is used (all standard design tokens
 *   with MUI defaults for palette, typography, spacing, breakpoints, shadows, shape).
 * @param props.children - React node tree that will receive the theme context.
 *   All descendant components gain access to theme tokens via MUI's context.
 * @returns A React JSX element wrapping children with the MUI theme context
 *   and CssBaseline normalization.
 */
export const ThemeProvider = ({
  theme,
  children,
}: ThemeProviderProps): React.JSX.Element => {
  // Resolve the theme: use the consumer-provided theme if available,
  // otherwise fall back to the library's default theme generated by
  // createCustomTheme() with no overrides.
  const resolvedTheme = theme ?? createCustomTheme();

  return (
    <MUIThemeProvider theme={resolvedTheme}>
      {/* CssBaseline injects a consistent CSS baseline (normalize/reset)
          inside the theme provider so it can access theme tokens for
          body background color, font family, and other global styles. */}
      <CssBaseline />
      {children}
    </MUIThemeProvider>
  );
};

// ---------------------------------------------------------------------------
// Display Name for React DevTools
// ---------------------------------------------------------------------------

/**
 * Display name for React DevTools debugging.
 * Ensures the component appears as "ThemeProvider" in the component tree
 * rather than an anonymous function reference.
 */
ThemeProvider.displayName = 'ThemeProvider';
